### ISSUE TITLE
integration broken after upgrade to 0.2.2

### ISSUE THREAD

**Issue by prolife86** [wolffshots/hass-audiobookshelf#21]
## System Information

version | core-2024.11.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.106-Unraid
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4947
Installed Version | 2.0.1
Stage | running
Available Repositories | 1462
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 14
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 November 2024 at 10:28
-- | --
current_recorder_run | 22 November 2024 at 10:47
estimated_db_size | 1469.59 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration is not loading devices nor sensors after upgrade to 0.2.2

![Schermafbeelding 2024-11-22 105248](https://github.com/user-attachments/assets/f390e05b-6813-4fa1-afeb-d7f0d1cf6809)
[home-assistant_audiobookshelf_2024-11-22T09-53-56.869Z.log](https://github.com/user-attachments/files/17868291/home-assistant_audiobookshelf_2024-11-22T09-53-56.869Z.log)

### Reproduction steps

1. Upgrade to 0.2.2 -> device error
2. remove device and remove 0.2.2 via HACS and reboot
3. reinstall 0.2.2 via HACS
4. Setup login details
a. IP: "http://192.168.1.104" or "https://audiobooks.XXX.nl" both give the same result
b. API key was copied from the admin user
c. scan interval 300 or 10 gives the same result.
5. not loading device nor sensors

### Debug logs

```text
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:365
integration: Sensor (documentation, issues)
First occurred: 10:48:48 (1 occurrences)
Last logged: 10:48:48

Error while setting up audiobookshelf platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/audiobookshelf/sensor.py", line 144, in async_setup_entry
    libraries: list[Library] = await coordinator.get_libraries()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiobookshelf/sensor.py", line 263, in get_libraries
    from_dict(
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 64, in from_dict
    value = _build_value(type_=field_type, data=field_data, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 99, in _build_value
    data = from_dict(data_class=type_, data=data, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "settings.audiobooks_only"
```

### Diagnostics dump

Not possible, as this button is not available on the integration.

**Comment by wolffshots** [comment]
Oops, I didn't mean for that PR to close this. I have made the fields on the libraries optional and published a new release for [v0.2.3](https://github.com/wolffshots/hass-audiobookshelf/releases/tag/v0.2.3). Please let me know if it still fails to set up.

The issue is that the API replies with slightly different data depending on what type of library it is fetching for and when I try cast that to my static Library type it will fail if a field is missing that it expects to be there.

**Comment by prolife86** [comment]
@wolffshots 
![Schermafbeelding 2024-11-22 155229](https://github.com/user-attachments/assets/7c3247a9-b5cb-46a4-9a45-4643719edd75)
Works perfect now, many thanks!
And that was a very fast resolution! :)

**Comment by wolffshots** [comment]
Sure thing, glad to get you sorted :)
